common/models/Battery.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use yz\shoppingcart\CartPositionInterface;
use yz\shoppingcart\CartPositionTrait;

/**
 * This is the model class for table "battery".
 *
 * @property integer $id
 * @property integer $parent_brend_id
 * @property string $title
 * @property integer $price
 * @property integer $old_price
 * @property string $currency
 * @property string $picture
 * @property string $model
 * @property integer $delivery
 * @property string $ostatok
 * @property string $article
 * @property string $capacity
 * @property string $current
 * @property string $polarity
 * @property integer $length
 * @property integer $width
 * @property integer $height
 * @property string $country
 * @property string $assurance
 * @property integer $voltage
 * @property integer $status
 * @property string $code
 * @property string $url
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 */
class Battery extends \yii\db\ActiveRecord implements CartPositionInterface
{
  use CartPositionTrait;
  /**
   * @getId для корзины
   */

  public function getId()
  {
    return 'battery-'.$this->id;
  }
  public function getPrice(){
    return $this->price;
  }
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'battery';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['parent_brend_id', 'title', 'picture', 'ostatok', 'capacity', 'current', 'polarity', 'voltage', 'code'], 'required'],
      [['parent_brend_id', 'price', 'old_price', 'delivery', 'length', 'width', 'height', 'voltage', 'status'], 'integer'],
      [['model','description'], 'string'],
      [['title', 'picture', 'country', 'assurance', 'url', 'meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255],
      [['currency'], 'string', 'max' => 10],
      [['ostatok', 'article', 'capacity', 'current', 'polarity', 'code'], 'string', 'max' => 25],
    ];
  }
  
  // public function behaviors()
  // {
  //   return [
  //     [
  //       'class' => SluggableBehavior::className(),
  //       // 'attribute' => 'title',
  //       'immutable' => true,
  //       'ensureUnique' => true,
  //       'slugAttribute' => 'url',
  //       'value' => function($event){
  //         $search = [' ','(',')','/','.','а','e','й','o','у','ш','э','б','ё','к','п','ф','щ','ю','в','ж','л','р','х','ъ','г','з','м','с','ц','ы','д','и','н','т','ч','ь','я'];
  //         $replace = ['-','','','-','','a','e','y','o','u','sh','e','b','e','k','p','f','shch','yu','v','zh','l','r','h','','g','z','m','s','ts','y','d','i','n','t','ch','','ya'];
  //         return trim(str_replace($search, $replace, mb_strtolower($event->sender->title)));
  //       },
  //     ],
  //   ];
  // }
  /**
   * @inheritdoc
   */

  public function getPicture(){
    $picture =  substr(strrchr($this->picture, '.'), 1);
    $picture = $picture != '' ? $this->picture : '/upload/none_pic.jpg';
    return $picture;
  }
  
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'parent_brend_id' => 'Бренд',      
      'title' => 'Заголовок',
      'price' => 'Цена',
      'old_price' => 'Старая Цена',
      'currency' => 'Валюта',
      'picture' => 'Изображение',
      'model' => 'Наименование',
      'delivery' => 'Доставка',
      'ostatok' => 'В наличии',
      'article' => 'Артикул',
      'capacity' => 'Ёмкость',
      'current' => 'Стартовый ток',
      'polarity' => 'Полярность',
      'length' => 'Длина',
      'width' => 'Ширина',
      'height' => 'Высота',
      'country' => 'Страна',
      'assurance' => 'Гарантия',
      'voltage' => 'Напряжение',
      'status' => 'Статус',
      'code' => 'Код',
      'url' => 'Url адрес',
      'meta_title' => 'Сео заголовок',
      'meta_keywords' => 'Сео теги',
      'meta_description' => 'Сео описание',
      'description' => 'Описание',
    ];
  }
  public function generateUrl($attr){
    $search = [' ','+',',','кг.','км.','/4х4',' ','(',')','/','.','а','е','й','о','у','ш','э','б','ё','к','п','ф','щ','ю','в','ж','л','р','х','ъ','г','з','м','с','ц','ы','д','и','н','т','ч','ь','я'];
    $replace = ['','','','kg','km','','-','','','-','-','a','e','y','o','u','sh','e','b','e','k','p','f','shch','yu','v','zh','l','r','h','','g','z','m','s','ts','y','d','i','n','t','ch','','ya'];
    return str_replace($search, $replace, mb_strtolower(trim($attr)));
  }
  public function getBrend(){
    return $this->hasOne(Brend::className(), ['id' => 'parent_brend_id']);
  }
  public function getDescription(){
    return $this->hasOne(Description::className(), ['code' => 'code']);
  }
  public function loadPitstop($model) {
    if($brend = Brend::find()->where(['title' => $model->a_brand])->one()){
      $this->parent_brend_id = $brend->id;
    } else {
      $brend = new Brend();
      $brend->title = $model->a_brand;
      $brend->url = $brend->generateUrl($model->a_brand);
      $brend->save();
      $this->parent_brend_id = $brend->id;
    }
    $this->title = $model->a_name;
    $this->price = $model->a_price;
    $this->old_price = $model->a_price1;
    $this->currency = 'KZT';
    $this->picture = $model->a_img;
    $this->model = $model->a_brand;
    $this->delivery = 1;
    $this->ostatok = $model->a_kol;
    $this->article = $model->a_act;
    $this->capacity = $model->a_em;
    $this->current = $model->a_tok;
    $this->polarity = $model->a_pol;
    $this->length = $model->a_length;
    $this->width = $model->a_width;
    $this->height = $model->a_height;
    $this->country = $model->a_proiz;
    $this->assurance = $model->a_gar;
    $this->voltage = $model->a_nap;
    $this->status = 1;
    $this->code = $model->a_1c;
    $this->url = $this->generateUrl($model->a_brand." ".$this->title." ".$this->code);
  }
}

backend/controllers/BatteryController.php
<?php
namespace backend\controllers;

use Yii;
use backend\models\SearchBattery;
use common\models\Disc;
use common\models\Oil;
use common\models\Battery;
use backend\components\BaseController;

/**
 * Battery controller
 */
class BatteryController extends BaseController
{
  public function actionIndex()
  {
    $searchModel = new SearchBattery();
    $models = $searchModel->search(Yii::$app->request->get());  
    return $this->render('index',compact(['models','searchModel']));
  }
}

frontend/controllers/BatteryController.php
<?php
namespace frontend\controllers;

use frontend\components\BaseController;

use common\models\SearchBattery;
use common\models\Battery;
use common\models\Oil;

/**
 * Battery controller
 */
class BatteryController extends BaseController
{
  /**
   * Displays homepage.
   *
   * @return mixed
   */
  public function actionIndex($params)
  {        
    $data = explode(";",$params);
    $search=[];
    if(count($data) > 0)
    for ($i=0; $i <= count($data); $i++) {
      $search = $this->getParams($data[$i],$search);
    }  
    $searchModel = new SearchBattery();
    $battery = $searchModel->search($search);
    $oil = Oil::find()->limit(20)->all();
    return $this->render('index',compact('battery','oil','searchModel'));
  }

  public function actionDetail($params='')
  { 
    if($params != ''){
      if($model = Battery::find()->where('url=:url',[':url'=>$params])->one()){
        return $this->render('detail',compact('model'));        
      }else{
        throw new \yii\web\NotFoundHttpException('По вашему запросу ничего не найдено!');
      }
    } 
    throw new \yii\web\NotFoundHttpException('По вашему запросу ничего не найдено!');     
  }
  public function actionFilter($capacity='',$current='',$polarity='',$length='',$width='',$height='',$country='',$assurance='',$voltage=''){
    // $row = 'capacity';
    // $row = 'current';
    // $row = 'polarity';
    // $row = 'length';
    // $row = 'width';
    // $row = 'height';
    // $row = 'country';
    // $row = 'assurance';
    // $row = 'voltage';
    // $file;
    // $m = Battery::find()->select($row)->where(['>','ostatok',0])->andWhere(['>','price',0])->orderBy($row)->groupBy($row)->all();
    // $file .= "['all'=>'Все'";
    // foreach($m as $model){
    //   if($model->$row == '')
    //     continue;
    //   $file .= ",'".$model->generateUrl($model->$row)."'=>'".$model->$row."'";
    // } 
    // $file .= "];";
    // file_put_contents('battery.txt',$file);
    // return;
    $where = [];
    $option['capacity'][] = ['key'=>'all','val'=>'Все'];
    $option['current'][] = ['key'=>'all','val'=>'Все'];
    $option['polarity'][] = ['key'=>'all','val'=>'Все'];
    $option['length'][] = ['key'=>'all','val'=>'Все'];
    $option['width'][] = ['key'=>'all','val'=>'Все'];
    $option['height'][] = ['key'=>'all','val'=>'Все'];
    $option['country'][] = ['key'=>'all','val'=>'Все'];
    $option['assurance'][] = ['key'=>'all','val'=>'Все'];
    $option['voltage'][] = ['key'=>'all','val'=>'Все'];
    $search = new SearchBattery();
    if($capacity != 'all'){$where['capacity'] = $search->_capacity[$capacity];}
    if($current != 'all'){$where['current'] = $search->_current[$current];}
    if($polarity != 'all'){$where['polarity'] = $search->_polarity[$polarity];}
    if($length != 'all'){$where['length'] = $search->_length[$length];}
    if($width != 'all'){$where['width'] = $search->_width[$width];}
    if($height != 'all'){$where['height'] = $search->_height[$height];}
    if($country != 'all'){$where['country'] = $search->_country[$country];}
    if($assurance != 'all'){$where['assurance'] = $search->_assurance[$assurance];}
    if($voltage != 'all'){$where['voltage'] = $search->_voltage[$voltage];}

    if($m = Battery::find()->select('capacity')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('capacity')->all()){
      foreach($m as $model){
        if($model->capacity == '')
          continue;
        $option['capacity'][] = ['key'=>$model->generateUrl($model->capacity),'val'=>$model->capacity];
      }      
    }
    if($m = Battery::find()->select('current')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('current')->all()){
      foreach($m as $model){
        if($model->current == '')
          continue;
        $option['current'][] = ['key'=>$model->generateUrl($model->current),'val'=>$model->current];
      }      
    }
    if($m = Battery::find()->select('polarity')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('polarity')->all()){
      foreach($m as $model){
        if($model->polarity == '')
          continue;
        $option['polarity'][] = ['key'=>$model->generateUrl($model->polarity),'val'=>$model->polarity];
      }      
    }
    if($m = Battery::find()->select('length')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('length')->all()){
      foreach($m as $model){
        if($model->length == '')
          continue;
        $option['length'][] = ['key'=>$model->generateUrl($model->length),'val'=>$model->length];
      }      
    }
    if($m = Battery::find()->select('width')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('width')->all()){
      foreach($m as $model){
        if($model->width == '')
          continue;
        $option['width'][] = ['key'=>$model->generateUrl($model->width),'val'=>$model->width];
      }      
    }
    if($m = Battery::find()->select('height')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('height')->all()){
      foreach($m as $model){
        if($model->height == '')
          continue;
        $option['height'][] = ['key'=>$model->generateUrl($model->height),'val'=>$model->height];
      }      
    }
    if($m = Battery::find()->select('country')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('country')->all()){
      foreach($m as $model){
        if($model->country == '')
          continue;
        $option['country'][] = ['key'=>$model->generateUrl($model->country),'val'=>$model->country];
      }      
    }
    if($m = Battery::find()->select('assurance')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('assurance')->all()){
      foreach($m as $model){
        if($model->assurance == '')
          continue;
        $option['assurance'][] = ['key'=>$model->generateUrl($model->assurance),'val'=>$model->assurance];
      }      
    }
    if($m = Battery::find()->select('voltage')->where($where)
      ->andWhere(['>','ostatok',0])->andWhere(['>','price',0])->groupBy('voltage')->all()){
      foreach($m as $model){
        if($model->voltage == '')
          continue;
        $option['voltage'][] = ['key'=>$model->generateUrl($model->voltage),'val'=>$model->voltage];
      }      
    }

    return json_encode($option,JSON_UNESCAPED_UNICODE);
  }

  private function getParams($params,$search){
    if(preg_match('/sorter[\w\-]+/', $params)){$search['sorter'] = str_replace('sorter-','',$params);}
    if(preg_match('/capacity[\w\-]+/', $params)){$search['capacity'] = str_replace('capacity-','',$params);}
    if(preg_match('/current[\w\-]+/', $params)){$search['current'] = str_replace('current-','',$params);}
    if(preg_match('/polarity[\w\-]+/', $params)){$search['polarity'] = str_replace('polarity-','',$params);}
    if(preg_match('/length[\w\-]+/', $params)){$search['length'] = str_replace('length-','',$params);}
    if(preg_match('/width[\w\-]+/', $params)){$search['width'] = str_replace('width-','',$params);}
    if(preg_match('/height[\w\-]+/', $params)){$search['height'] = str_replace('height-','',$params);}
    if(preg_match('/country[\w\-]+/', $params)){$search['country'] = str_replace('country-','',$params);}
    if(preg_match('/assurance[\w\-]+/', $params)){$search['assurance'] = str_replace('assurance-','',$params);}
    if(preg_match('/voltage[\w\-]+/', $params)){$search['voltage'] = str_replace('voltage-','',$params);}
    if(preg_match('/brend[\w\-]+/', $params)){
      $search['brend'] = str_replace('brend-','',$params);
      $session['filter-shiny'] = 'auto';
    }
    return $search;
  }
}

frontend/views/battery/detail.php
<?php
use frontend\widgets\MenuLeft;
use frontend\widgets\Cards;
use common\models\Battery;

$this->params['breadcrumbs'][] = ['label' => 'Аккумуляторы', 'url' => ['/battery/index']];
$this->registerJs("mastershina.controller('BatteryController', function() {
  var battery = this; 
  battery.ostatok = ".json_encode($model->ostatok == 'Нет в наличии' ? 0 : preg_replace("/\D/", "", $model->ostatok))."  
  battery.coll = parseInt(battery.ostatok) > 4 ? 4 : parseInt(battery.ostatok);
  battery.price = ".json_encode($model->price)."
  battery.priceOld = ".json_encode($model->old_price)."
  battery.bstyle = 'danger'
  // калькуляция
  battery.total = 0 // Общая сумма шин

  if(battery.ostatok > 0){battery.bstyle = 'success'}
  if(battery.ostatok > 0){battery.sklad = battery.ostatok}else{battery.sklad = 'нет'}

  battery.summer= function(){
    // Если вдруг кол шин больше чем остаток на складе
    if(battery.coll > parseInt(battery.ostatok)){
      battery.coll = battery.ostatok;
    }
    battery.total = battery.coll * battery.price;
  }

  battery.summer();

})", yii\web\View::POS_END);
?>
<div class="row" ng-controller="BatteryController as battery"> 
  <div class="col-md-3"><?= MenuLeft::widget()?></div>
  <!-- End New Arrivals & Best Selling -->
  <div class="clearfix visible-sm visible-xs"></div>
  <div class="col-md-9">
    <div class="row">
      <?= yii\widgets\Breadcrumbs::widget([
        'homeLink'      =>  [
          'label'     =>  Yii::t('yii', 'Главная'),
          'url'       =>  ['/'],
          // 'class'     =>  'home',
          'template'  =>  '<span class="glyphicon glyphicon-home"></span> {link}',
        ],
        'links' => $this->params['breadcrumbs'],
        'itemTemplate'  =>  ' / {link}',
        // 'tag'           =>  'ul',
      ])?>
      <div class="clearfix"></div>
      <!-- Image List -->
      <div class="col-sm-3">
        <div class="image-detail">      
          <img src="<?= $model->getPicture()?>" alt="">
        </div>
      </div>
      <!-- End Image List -->
      <div class="col-sm-9">
        <div class="title-detail"><?= $model->brend->title." ".$model->title ?></div>
        <table class="table table-detail">
          <tbody>
            <tr>
              <td>Цена</td>
              <td>
                <div class="price">
                  <div ng-bind-template="{{t(battery.price)}} со скидкой"></div>
                  <span class="price-old" ng-bind-template="{{t(battery.priceOld)}} в кредит"></span>
                </div>
              </td>
            </tr>
            <tr>
              <td>В наличии</td>
              <td>
                <!-- <div class="row">
                  <div class="col-md-2 col-sx-2"><span class="label label-{{battery.bstyle}} arrowed">{{battery.sklad}}</span></div>
                  <div class="col-md-10 col-sx-10">
                  </div>
                </div>  -->               
                <span class="label label-{{battery.bstyle}} arrowed" ng-bind="battery.sklad"></span>
                <a href="#" ng-hide="battery.ostatok > 0" data-toggle="modal" data-target="#myModal"><span class="label label-info">Сообщить о наличии</span></a>
                <div class="modal fade" id="myModal">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Сообщить о наличии</h4>
                      </div>
                      <div class="modal-body">
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="email или телефон для оповещения">                  
                           <span class="input-group-btn">
                            <button class="btn btn-theme" data-dismiss="modal" type="button"><i class="fa fa-envelope-o"></i> Отправить</button>
                          </span>
                        </div>
                      </div>
                      <!-- <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button type="button" class="btn btn-primary">Сохранить изменения</button>
                      </div> -->
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-12 col-lg-12" ng-show="battery.ostatok > 0">
        <div class="card-panel">
          <div class="row">
            <div class="col-md-6">
              <table>
                <tbody>              
                  <tr>
                    <td>Кол-во масел</td>
                    <td class="input-qty">
                      <input type="text" ng-model="battery.coll" ng-change="battery.summer()" class="form-control text-center"/>
                    </td>
                  </tr>
                  <tr> 
                    <td class="qty-res" ng-bind="t(battery.price)"></td> 
                    <td class="qty-total" ng-bind="t(battery.total)"></td>          
                  </tr>
                </tbody>
              </table>
              
            </div>
            <div class="col-md-3">
              <button class="btn btn-block btn-theme" ng-click="basket.putCart(<?= $model->id;?>,'battery',battery.coll)" type="button"><i class="fa fa-shopping-cart"></i> В корзину</button>
            </div>
            <div class="col-md-3">
              <!-- <button class="btn btn-block btn-theme" disabled type="button"><i class="fa fa-money"></i> Купить кредит</button> -->
              <a href="/service/delivery" class="btn">Доставка</a>
              <a disabled class="btn"><i class="fa fa-user-md"></i> Консультация</a>
            </div>
          </div>      
        </div>
      </div>
      <div class="col-md-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#detail" aria-controls="detail" role="tab" data-toggle="tab">Характеристики</a></li>
        </ul>
        <!-- End Nav tabs -->
        <!-- Tab panes -->
        <div class="tab-content tab-content-detail">

            <!-- Detail Tab Content -->
            <div role="tabpanel" class="tab-pane active" id="detail">
              <div class="well">
                <table class="table table-bordered">
                  <tbody>
                    <tr>
                      <td><?= $model->getAttributeLabel('article')?></td>
                      <td><?= $model->article?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('capacity')?></td>
                      <td><?= $model->capacity?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('current')?></td>
                      <td><?= $model->current?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('polarity')?></td>
                      <td><?= $model->polarity?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('length')?></td>
                      <td><?= $model->length?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('width')?></td>
                      <td><?= $model->width?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('height')?></td>
                      <td><?= $model->height?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('country')?></td>
                      <td><?= $model->country?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('assurance')?></td>
                      <td><?= $model->assurance?></td>
                    </tr>
                    <tr>
                      <td><?= $model->getAttributeLabel('voltage')?></td>
                      <td><?= $model->voltage?></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <!-- End Detail Tab Content -->
            <?php if($model->description->text != null):?>
              <div class="title"><span>Описание</span></div>
              <div class="tab-pane active">
                <div class="well"><?= $model->description->text ?></div>
              </div>
            <?php endif;?>
        </div>
        <!-- End Tab panes -->
      </div>
      
      <div class="clearfix visible-sm visible-xs"></div>
      <?php 
      $disc = Battery::find()->where(['capacity'=>$model->capacity,'current'=>$model->current,'length'=>$model->length,'width'=>$model->width,'height'=>$model->height,'voltage'=>$model->voltage])
        ->andWhere(['!=','url',$model->url])
        ->andWhere(['>','price',0])
        ->andWhere(['>','ostatok',0])
        ->orderBy(['price'=>SORT_DESC])->all();
      if($disc):
      ?>
      <div class="col-md-12">
        <div class="title"><span>Похожие товары</span></div>
        <div class="product-slider owl-controls-top-offset">
          <?php foreach ($disc as $model):?>
            <div class="box-product-outer">            
              <?= Cards::widget([
                'model'=>$model,
                'link'=> '/oil/detail/'.$model->url,
                // 'sale'=>['title'=> 'Акция','style'=>'danger'],
                // 'featured'=>['title'=> 'Рекомендуемые','style'=>'default'],
                // 'rating'=>['count'=>5,'rating'=>4],
              ])?>
            </div>
          <?php endforeach;?>
        </div>
      </div>
      <?php endif;?>
    </div>
  </div>
</div>

frontend/views/battery/index.php
<?php
use yii\helpers\Url;
use frontend\widgets\MenuLeft;
use frontend\widgets\Cards;
/* @var $this yii\web\View */
$this->title = 'Блог от интернет-магазина МастерШина';
?>
  <!-- <div class="row">
    <div class="col-md-12">
      <div class="title"><span><a href="products.html">Фильтр <i class="fa fa-chevron-circle-right"></i></a></span></div>
    </div>
  </div> -->
  <div class="row">
    <div class="col-md-3"><?= MenuLeft::widget()?></div>
    <!-- End New Arrivals & Best Selling -->
    <div class="clearfix visible-sm visible-xs"></div>
    <div class="col-md-9">
      <?= \frontend\widgets\SearchFormBattery::widget(['model'=>$searchModel])?> 
      <!-- Featured -->
      <div class="title"><span>Каталог Акумуляторов</span></div>
      <?= yii\widgets\ListView::widget([        
        'dataProvider' => $battery,
        'itemView' => function($model){
          return Cards::widget([
            'category'=>'battery',
            'model'=>$model,
            'link'=> '/battery/detail/'.$model->url,
            // 'sale'=>['title'=> 'Акция','style'=>'danger'],
            // 'featured'=>['title'=> 'Рекомендуемые','style'=>'default'],
            // 'rating'=>['count'=>5,'rating'=>4],
          ]);
        },
        'itemOptions' => [
            'tag' => 'div',
            'class' => 'col-sm-4 col-lg-3 box-product-outer',
        ],
        'layout' => "{summary}<div class='clearfix'></div>{items}<div class='clearfix'></div>{pager}", // "{sorter}\n{summary}\n{items}\n{pager}
        'summary' => "Показано {count} из {totalCount}",
        'emptyText' => 'Ничего не найдено',

      ]);?>
      <!-- End Featured -->
      <div class="clearfix visible-sm visible-xs"></div>
      <!-- Collection -->
      <div class="title m-t-2"><span>Рекомендуем к этому товару</span></div>
      <div class="product-slider owl-controls-top-offset">
        <?php foreach ($oil as $model):?>
          <div class="box-product-outer">            
            <?= Cards::widget([
              'category'=>'oil',
              'model'=>$model,
              'link'=> '/oil/detail/'.$model->url,
              // 'sale'=>['title'=> 'Акция','style'=>'danger'],
              // 'featured'=>['title'=> 'Рекомендуемые','style'=>'default'],
              // 'rating'=>['count'=>5,'rating'=>4],
            ])?>
          </div>
        <?php endforeach;?>
      </div>
      <!-- End Collection -->
    </div>
  </div>